<%-- <script src="<%=request.getContextPath() %>/js/jquery.min.js"></script>
<script src="<%=request.getContextPath() %>/css/bootstrap/js/bootstrap.min.js"></script>
<script src="<%=request.getContextPath() %>/css/bootstrap/js/bootstrap-switch.js"></script> --%>

    <script type="text/javascript" src="<%=request.getContextPath() %>/js/jquery.min.js"></script>	   
    <script type="text/javascript" src="<%=request.getContextPath() %>/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="<%=request.getContextPath() %>/js/modules.js"></script>	
	<script type="text/javascript" src="<%=request.getContextPath() %>/js/theme.js"></script> 
    <script type="text/javascript" src="<%=request.getContextPath() %>/js/color_panel.js"></script>
    <script type="text/javascript" src="<%=request.getContextPath() %>/js/jquery.themepunch.plugins.min.js"></script>
    <script type="text/javascript" src="<%=request.getContextPath() %>/js/jquery.themepunch.revolution.min.js"></script>   
    <script type="text/javascript" src="<%=request.getContextPath() %>/js/jquery.isotope.min.js"></script>
    <script type="text/javascript" src="<%=request.getContextPath() %>/js/sorting.js"></script>
