<meta http-equiv="Content-Language" content="zh-cn">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<%-- <link rel="shortcut icon" href="<%=request.getContextPath() %>/img/favicon.png" type="image/x-icon"> --%>
<link rel="shortcut icon" href="<%=request.getContextPath() %>/${FAVICONURL}" type="image/x-icon">
<link rel="apple-touch-icon" href="<%=request.getContextPath() %>/img/apple_icons_57x57.png">
<link rel="apple-touch-icon" sizes="72x72" href="<%=request.getContextPath() %>/img/apple_icons_72x72.png">
<link rel="apple-touch-icon" sizes="114x114" href="<%=request.getContextPath() %>/img/apple_icons_114x114.png">

<link rel="stylesheet" href="<%=request.getContextPath() %>/css/roboto.css" type="text/css">
<link rel="stylesheet" href="<%=request.getContextPath() %>/css/nothing.css"  type="text/css">
<link rel="stylesheet" href="<%=request.getContextPath() %>/css/bootstrap.min.css" type="text/css" media="all" />
<link rel="stylesheet" href="<%=request.getContextPath() %>/css/theme.css" type="text/css" media="all" />
<link rel="stylesheet" href="<%=request.getContextPath() %>/css/revslider.css" type="text/css" media="all" />
<link rel="stylesheet" href="<%=request.getContextPath() %>/css/custom.css" type="text/css" media="all" />