<!DOCTYPE html>
<%@ page language="java" pageEncoding="UTF-8"%>
<%@ page contentType="text/html;charset=UTF-8"%>

<table border="1" width="100%">
	 <div class="footer">
    	<div class="container">
        	<div class="pre_footer">
            	<div class="row">
                	<div class="col-sm-6">
                    	<div class="sidepanel widget_text">
                        	<h4 class="title">联系我们</h4>
                        	<p><span>电话:</span>${aboutus.imageurl}</p>
                            <p><span>地址:</span> ${aboutus.title}</p>
                           <!--  <p><span>邮箱:</span> 1722205782@qq.com</p> -->
                            
                        </div>	
                    </div>
                    
                </div>
            </div>
            <div class="footer_bottom">
            	<div class="copyright">
            	${menu.name}
            	</div>
            </div>
        </div>
    </div>