<%-- <script src="<%=request.getContextPath() %>/js/jquery.min.js"></script>
<script src="<%=request.getContextPath() %>/css/bootstrap/js/bootstrap.min.js"></script>
<script src="<%=request.getContextPath() %>/css/bootstrap/js/bootstrap-switch.js"></script> --%>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/jquery-2.1.1.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/jquery-2.0.3.min.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/jquery.mobile.custom.min.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/ace-extra.min.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/bootstrap-3.3.4.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/typeahead-bs2.min.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/jquery-ui-1.10.3.custom.min.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/jquery.ui.touch-punch.min.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/jquery.slimscroll.min.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/jquery.easy-pie-chart.min.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/jquery.sparkline.min.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/flot/jquery.flot.min.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/flot/jquery.flot.pie.min.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/flot/jquery.flot.resize.min.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/ace-elements.min.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/ace.min.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/jquery.dataTables.min.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/jquery.dataTables.bootstrap.js"></script>


 <%-- 2017-10-13--%>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/markdown/markdown.min.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/markdown/bootstrap-markdown.min.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/third-party/temptlate.min.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/umeditor.config.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/umeditor.min.js"></script>
<script src="<%=request.getContextPath() %>/jsp/ht/assets/js/zh-cn/zh-cn.js" ></script>
