<meta http-equiv="Content-Language" content="zh-cn">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="shortcut icon" href="<%=request.getContextPath() %>/img/favicon.png" type="image/x-icon">
<link rel="apple-touch-icon" href="<%=request.getContextPath() %>/img/apple_icons_57x57.png">
<link rel="apple-touch-icon" sizes="72x72" href="<%=request.getContextPath() %>/img/apple_icons_72x72.png">
<link rel="apple-touch-icon" sizes="114x114" href="<%=request.getContextPath() %>/img/apple_icons_114x114.png">
<link rel="stylesheet" type="text/css" href="<%=request.getContextPath() %>/jsp/ht/assets/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="<%=request.getContextPath() %>/jsp/ht/assets/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="<%=request.getContextPath() %>/jsp/ht/assets/css/ace.min.css" />
<link rel="stylesheet" type="text/css" href="<%=request.getContextPath() %>/jsp/ht/assets/css/ace-rtl.min.css" />
<link rel="stylesheet" type="text/css" href="<%=request.getContextPath() %>/jsp/ht/assets/css/ace-skins.min.css" />




<link rel="stylesheet" type="text/css" href="<%=request.getContextPath() %>/jsp/ht/assets/css/umeditor.css" />
<link rel="stylesheet" type="text/css" href="<%=request.getContextPath() %>/jsp/ht/assets/css/umeditor.min.css" />